SmartSys/Controllers/Visita/VisitaController.cs
using SmartSys.Models;
using SmartSys.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using OfficeOpenXml;
using System.IO;
using ApiMailsender;
using SmartSys.Models.Clases;

namespace SmartSys.Controllers.Visita
{
    public class VisitaController : Controller
    {

        DB_Smartsys3Entities db = new DB_Smartsys3Entities();
        SendEmailAndAppoiment appoiment = new SendEmailAndAppoiment();
        public ActionResult Index()
        {
            ViewBag.Motivo = new SelectList(db.TBL_Motivo_Visita, "ID_Motivo", "Motivo");

            return View();
        }



        public ActionResult CreateVisita()
        {

            ViewBag.Motivo = new SelectList(db.TBL_Motivo_Visita, "ID_Motivo", "Motivo");
            ViewBag.EstadoVisita = new SelectList(db.TBL_Estado_Visita, "ID_Estado_Visita", "Estado_Visita");

            if (db.TBL_Visita.Any(c => c.ID_Visita > 0))
            {
                ViewBag.VisitaNum = db.TBL_Visita.Max(c => c.ID_Visita) + 1;
            }
            else
            {
                ViewBag.VisitaNum = 1;
            }

            return View();
        }


        [HttpPost]
        public ActionResult CreateVisita(string Motivo,
        string Contacto,
        string Lugar,
        string Fecha,
        string HoraInicio,
        string HoraFin,
        string Asunto,
        string Comentario,
        int Responsable,
        string Integrantes,
        int Cliente)
        {
            var tipo = "";
            List<string> ListEmail = new List<string>();

            ViewBag.Motivo = new SelectList(db.TBL_Motivo_Visita, "ID_Motivo", "Motivo", Motivo);
            try
            {
                db.SP_SAVE_VISITA(
                                Contacto, Convert.ToInt32(Motivo), 1, Convert.ToInt32(Session["IdUsuario"]), Lugar, DateTime.Parse(Fecha)
                                , DateTime.Now, Asunto, Comentario, HoraInicio, HoraFin, Responsable,Cliente
                                );
                if (Integrantes != null)
                {
                    var IDVisita = db.TBL_Visita.Max(e => e.ID_Visita).ToString();
                    var visitaid = Convert.ToInt32(IDVisita);                  
                    string data = Integrantes.ToString();
                    data = data.Remove(data.Length - 1);
                    string[] integrantesguardar = Regex.Split(data, ",");
                    foreach (var item in integrantesguardar)
                    {
                       
                        string nombre = item.Split('|')[0];
                        string codigoid = item.Split('|')[1];
                        db.SP_SaveItegrantes(Convert.ToInt32(IDVisita), nombre,codigoid, 1,1);

                        if (codigoid.Split('-')[0] == "ENT")
                        {
                            tipo = "Cliente";
                        }
                        else
                        {
                            tipo = "Usuario";
                        }
                        var query = db.SP_GetPersonaEmail(codigoid.Split('-')[1], tipo).ToList();
                        foreach (var i in query)
                        {
                            ListEmail.Add(i);
                        }
                        
                    }
                }
                var Mot = Convert.ToInt32(Motivo);
                var queryMotivo = db.TBL_Motivo_Visita.Where(e => e.ID_Motivo == Mot).ToList();
                var queryResponsableEmail = db.TBL_Usuario.Where(e => e.ID_Usuario == Responsable).Select(e => e.Email).ToList();
                ListEmail.Add(queryResponsableEmail[0]);
               

                var fechaDesde = Fecha + " " + HoraInicio;
                var fechaHasta = Fecha + " " + HoraFin;

                appoiment.AppoimentCreator("Visita convocatoria", queryMotivo[0].Motivo, queryResponsableEmail[0], ListEmail, DateTime.Parse(fechaDesde), DateTime.Parse(fechaHasta), Lugar);
                //newAPISoap newAPISoap = new newAPISoap();
                //    newAPISoap.AppoimentCreator("Visita convocatoria","edgar.aguasvivas@ros.com.do","Made-0910",queryMotivo[0].Motivo,ListEmail, DateTime.Parse(Fecha), DateTime.Parse(Fecha),"");

            }
            catch (Exception e)
            {
                return Json("0", JsonRequestBehavior.AllowGet);
                throw;
            }
            

            return Json("1",JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetData(string searchTerm, string tipo)
        {
            tipo = tipo.ToString();
            var data = db.SP_GetPersona(searchTerm, tipo).ToList();
            var modifiedData = data.Select(x => new
            {
                id = x.ID,
                text = x.NombreCompleto
            });

            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AgendarVisita(TBL_Integrantes_Visitas integrantes)
        {



            return View("Index");

        }

        [HttpGet]
        public ActionResult GetEvent(TBL_Visita visita)
        {

            var eventos = db.SP_GetDataVisitasEvent(Convert.ToInt32(Session["IdUsuario"])).Select(e => new
            {

                title = e.Titulo,
                start = e.FechaInicio,
                end = e.FechaFin,
                backgroundColor = e.Color

            });

            var row = eventos.ToArray();

            return Json(row, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetDetailVisita(int? id)
        {


            if (id != null)
            {
                var retorna = db.TBL_Visita.Where(e => e.ID_Visita == id).Select(e => new
                {
                    IdVisita = e.ID_Visita,
                    IdMotivo = e.ID_Motivo_Visita,
                    Motivo = e.TBL_Motivo_Visita.Motivo,
                    Contacto = e.Contacto,
                    Estado = e.TBL_Estado_Visita.Estado_Visita,
                    UsuarioCreador = e.TBL_Usuario.Nombre,
                    Direccion = e.Direccion,
                    Fecha_Inicio = SqlFunctions.DatePart("MM", e.Fecha_Inicio_Visita) + "/" + SqlFunctions.DateName("DD", e.Fecha_Inicio_Visita) + "/" + SqlFunctions.DateName("YYYY", e.Fecha_Inicio_Visita),
                    HoraInicio = e.Hora_Inicio,
                    HoraFin = e.Hora_Fin,
                    Asunto = e.Asunto,
                    Comentario = e.Comentario,
                    Responsable = e.TBL_Usuario1.Nombre,
                    Cliente = e.TBL_Ente.Nombre,
                    IdCliente = e.ID_Ente

                }).ToList();



                return Json(retorna, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(HttpNotFound(), JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult getIntegrantes(int? id)
        {
       
            var exist = db.TBL_Integrantes_Visitas.Where(e => e.ID_Visita == id && e.Condicion_Registro == "0").FirstOrDefault();         

            
            if (id != null && exist != null)
            {
                var log = db.TBL_Integrantes_Visitas.Where(e => e.ID_Visita == id).Max(e => e.Log_No);
                var retorna = db.TBL_Integrantes_Visitas.Where(e => e.ID_Visita == id && e.Log_No == log).Select(e => new
                {
                    IdIntegrante = e.ID_Integrantes_Visitas,
                    Integrante = e.Nombre_Integrante                    
                }).ToList();

                return Json(retorna, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
           
        }

        [HttpPost]
        public ActionResult EditarVisita(int IdVisita,int Motivo, string Contacto,string Lugar,string Asunto,string Comentario,string Integrantes,int Cliente)
        {
        
            ViewBag.Motivo = new SelectList(db.TBL_Motivo_Visita, "ID_Motivo", "Motivo", IdVisita);
            //DateTime fechaInicio = DateTime.ParseExact(FechaInicio, "dd-MM-yyyy", CultureInfo.InvariantCulture);
            //FechaInicio = fechaInicio.ToString("yyyy-MM-dd");

            //DateTime fechaFin = DateTime.ParseExact(FechaFin, "dd-MM-yyyy", CultureInfo.InvariantCulture);
            //FechaFin = fechaFin.ToString("yyyy-MM-dd");
            try
            {
                db.SP_EditarVisita(IdVisita, Motivo, Contacto, Lugar, Asunto, Comentario,Cliente);

                var exist = (from c in db.TBL_Integrantes_Visitas
                             where c.ID_Visita == IdVisita                            
                             select new { c.Log_No }).ToList();


                if (Integrantes != null)
                {
                    if (exist.Count != 0)
                    {

                        var log = db.TBL_Integrantes_Visitas.Where(e => e.ID_Visita == IdVisita).Max(e => e.Log_No) + 1;
                        string data = Integrantes.ToString();
                        data = data.Remove(data.Length - 1);
                        string[] integrantesguardar = Regex.Split(data, ",");

                        foreach (var item in integrantesguardar)
                        {
                            string nombre = item.Split('|')[0];
                            string codigoid = item.Split('|')[1];
                            db.SP_SaveItegrantes(IdVisita, nombre, codigoid, Convert.ToInt32(log), 0);
                        }

                    }
                    else
                    {
                        string data = Integrantes.ToString();
                        data = data.Remove(data.Length - 1);

SmartSys/Views/Visita/CreateVisita.cshtml
@model SmartSys.Models.TBL_Visita

@{
    ViewBag.Title = "CreateVisita";
}

<div class="container-fluid shadow overflow-auto">
    <form method="POST" id="formCrearVisita" action="" class="needs-validation" novalidate style="padding:50px;width: 85%;">
        @*@using (Html.BeginForm("CreateVisita", "Visita"))
        {*@
        <input type="hidden" id="VisitaNumero" value="@ViewBag.VisitaNum" />

        <div class="form-row">

            <div class="form-group col-md-6">
                <label class="col-12" for="Cliente">*Entidad</label>
                <input type="hidden" name="Cliente" id="idCliente" value="" />
                <select id="Cliente" class="form-control col-10 SelectCliente required">
                    <option></option>
                </select>
                @*<input type="text" class="form-control col-10 required" id="Cliente" name="" onkeypress="return pulsar(event)" placeholder="Buscar..." autocomplete="off">
        <ul id="result_Cliente" class="list-group" style="position:absolute;max-height:350px;z-index:1;width:415px; overflow:auto"></ul>*@
            </div>
            <div class="form-group col-md-6">
                <label for="idMovivoVisita">*Motivo Visita</label>
                @Html.DropDownList("Motivo", null, new { @class = "form-control select-normal col-10 required" })
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="idContactoVisita">*Contacto de la Visita</label>
                <input type="text" class="form-control col-10 required" id="ID_Contacto" onkeypress="return /[a-z,-/ ]/i.test(event.key)" name="ID_Contacto" placeholder="" required>
            </div>
            <div class="form-group col-md-6">
                <label class="" for="idLugarReunion">*Lugar de la Reunión</label>
                <textarea class="form-control col-10 required" id="idLugarReunion" name="Direccion" required></textarea>
            </div>
        </div>
        <br />
        <hr class="bg-black left" style=" box-shadow: 2px 1px 6px #000;" />
        <br />
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="idFechaInicio">*Fecha</label>
                <input type="date" class="form-control datepickerhtml col-6 required" onkeypress="return pulsar(event)" id="idFechaInicio" name="Fecha_Inicio_visita" onblur="validDateTime(this.value,this)" placeholder="">
            </div>

        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="" for="idHoraInicio">*Hora Inicio Visita</label>
                <input type="time" class="form-control col-6 required" onkeypress="return pulsar(event)" id="idHoraInicio" name="idHoraInicio">
            </div>
            <div class="form-group col-md-6">
                <label class="" for="idHoraFin">*Hora Fin Visita</label>
                <input type="time" class="form-control col-6 required" onkeypress="return pulsar(event)" id="idHoraFin" name="idHoraFin">
            </div>
            @*<div class="form-group col-md-3">
                <label class="" for="idHoraRealizada">Hora Visita Realizada</label>
                <input type="text" class="form-control" id="idHoraRealizada" name="idHoraRealizada" data-inputmask='"mask": "99:99:99"' data-mask>
            </div>*@
        </div>
        <br />
        <hr class="bg-black left" style=" box-shadow: 2px 1px 6px #000;" />
        <br />
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="" for="idAsunto">*Asunto</label>
                <textarea class="form-control col-10 required" id="idAsunto" name="Asunto" required></textarea>
            </div>
            @*<div class="form-group col-md-6">
                <label class="" for="idComentarioCierre">Comentario de Cierre</label>
                <textarea class="form-control" id="idComentarioCierre" name="idComentarioCierre"></textarea>
            </div>*@
            <div class="form-group col-md-6">
                <label class="" for="idComentarioGen">Comentario</label>
                <textarea class="form-control col-10" id="idComentarioGen" name="Comentario"></textarea>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="col-12" for="idAsunto">*Responsable</label>
                <select id="Responsable" class="form-control col-10 SelectResponsable required">
                    <option></option>
                </select>
                @*<input type="hidden" name="Responsable" id="idResponsable" value="" />
        <input type="text" class="form-control col-10 required" onkeypress="return pulsar(event)" id="Responsable" name="" placeholder="Buscar..." autocomplete="off" required>
        <ul id="result_Responsable" class="list-group" style="position:absolute;max-height:350px;z-index:1;width:415px; overflow:auto"></ul>*@
            </div>
        </div>

        <br />
        <hr class="bg-black left" style=" box-shadow: 2px 1px 6px #000;" />
        <br />
        <input type="text" hidden id="Integrantes" name="Nombre_Integrante" />
        <div class="form-row">
            <div class="col-md-12">
                <label for="IntegranteExt">Integrantes Externos</label>
            </div>
            <div class="col-md-5">
                <input type="text" class="form-control col-12"  onkeypress="return /[a-z, ]/i.test(event.key)" id="IntegranteExt" name="" placeholder="" autocomplete="off">

            </div>
            </div>
        <br />
            <div class="form-row">

         
                <div class="col-md-12">
                    <label for="searchIntegrante">Integrantes</label>
                </div>
                <div class="col-md-5">
                    <select id="Integrante" class="form-control col-10 SelectIntegrante required">
                        <option></option>
                    </select>
                    @*<input type="text" class="form-control col-12" onkeypress="return pulsar(event)" onkeyup="deleteValue(this)" id="searchIntegrante" name="" placeholder="Buscar..." autocomplete="off">
        <ul id="resultIntegrantes" class="list-group" style="position:absolute;max-height:350px;z-index:1;width:400px; overflow:auto"></ul>*@
                </div>
                <div class="col-md-2">
                    <input id="BotonAgregar" type="button" class="btn btn-dark add-row" value="Agregar">
                </div>

            </div>
            &nbsp;
            <table id="TableIntegrantes" class="table" width="100%">
                <thead class="thead-dark">
                    <tr>                     
                        <th>
                            Integrantes
                        </th>
                        <th>
                            ...
                        </th>
                    </tr>
                </thead>
                <tbody id="tbodyIntegranteCrear"></tbody>
            </table>
            <div class="bg-dark">
                <button class="btn btn-success btnfloat"
                        style="
            position: fixed;
             width:100px;
            bottom: 50%;
            right: 40px;
            text-align: center;
            box-shadow: 2px 2px 3px #999;" id="guardarvisita">
                    Guardar
                </button>
                <a class="btn btn-info btnfloat" href="#"
                   style="
            position: fixed;
            width:100px;
            bottom: 42%;
            right: 40px;
            text-align: center;
            box-shadow: 2px 2px 3px #999;" onclick="CleanForms('formCrearVisita')">Limpiar</a>
                <a class="btn btn-primary btnfloat" href="Index"
                   style="
            position: fixed;
             width:100px;
            bottom: 34%;
            right: 40px;
            text-align: center;
            box-shadow: 2px 2px 3px #999;">Volver</a>
            </div>


    </form>

    </div>

<style>
    /* The container */
    .container {
        display: block;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 22px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

        /* Hide the browser's default checkbox */
        .container input {
            position: absolute;
            opacity: 0;
            cursor: pointer;
            height: 0;
            width: 0;
        }

    /* Create a custom checkbox */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 25px;
        width: 25px;
        background-color: #eee;
    }

    /* On mouse-over, add a grey background color */
    .container:hover input ~ .checkmark {
        background-color: #ccc;
    }

    /* When the checkbox is checked, add a blue background */
    .container input:checked ~ .checkmark {
        background-color: #2196F3;
    }

    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the checkmark when checked */
    .container input:checked ~ .checkmark:after {
        display: block;
    }

    /* Style the checkmark/indicator */
    .container .checkmark:after {
        left: 9px;
        top: 5px;
        width: 5px;
        height: 10px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
</style>