SmartSys/Controllers/Digitalizacion/DigitalizacionController.cs
using SmartSys.Models;
using SmartSys.Models.Clases;
using SmartSys.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Permissions;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace SmartSys.Controllers.Digitalizacion
{
    public class DigitalizacionController : Controller
    {
        AdoConnections.conneciones referencia = new AdoConnections.conneciones();
        DB_Smartsys3Entities db = new DB_Smartsys3Entities();
        string Localpoliza;


        #region Vistas Digitalizacion

        // GET: Digitalizacion

        // carga de la pagina de Digitalizacion
        public ActionResult Inicio()
        {
            //Limpiamos los archivos temporales_____________________//

            erasetemp();
            return View();


        }

        [HttpPost]
        public void erasetemp()
        {
            string ruta = Server.MapPath("/Temporal");
            var directorio = new DirectoryInfo(ruta);
            try
            {

                foreach (FileInfo fi in directorio.GetFiles())
                {

                    fi.Delete();
                }

                foreach (DirectoryInfo di in directorio.GetDirectories())
                {

                    Directory.Delete(di.FullName.ToString(), true);
                }
                //if (directorio.Exists == true)
                //{
                //    Directory.Delete(directorio.ToString(), true);
                //}


            }
            catch (Exception)
            {

            }
        }
        //Action 
        //consulta si hay archivos en la carpeta temporal......///
        [HttpPost]
        public JsonResult FileConsult(string polizza)
        {
            int cont = 0;
            bool response = false;
            string fecha = DateTime.Now.ToString("dd-MM-yyyy");
            try
            {
                string source = Server.MapPath("/App_Data/Temporal/RosTemp_Digitalizacion/" + fecha + "/" + polizza);
                var datasrouce = new DirectoryInfo(source);


                foreach (var item in datasrouce.GetFiles())
                {
                    cont++;
                }
                if (cont != 0)
                {
                    response = true;

                }
                else
                {
                    response = false;
                }
            }
            catch (Exception ex)
            {
                response = false;
            }
            finally
            {

            }
            return Json(response);


        }
        [HttpPost]
        public JsonResult uploadfile()
        {
            string[] respuesta = new string[2];
            /// Primero traemos el documentos adjunto y la poliza desde el front_____!
            string listFilesToDelete = "";


            HttpFileCollectionBase files = Request.Files;
            string paliza = Request.Form["Id"].ToString();
            //HttpPostedFileBase onfile = files["data"];
            int Num = Convert.ToInt32(Request.Form["datalengh"]);
            Localpoliza = paliza;


            List<HttpPostedFileBase> onfile2 = new List<HttpPostedFileBase>();

            for (int i = 0; i < Num; i++)
            {
                onfile2.Add(files["data" + i]);

            }


            /// Tomamos la fecha sin la hora_____!
            string Time = DateTime.Now.ToString("dd-MM-yyyy");
            string ruta = @"//172.16.32.35/Digitalizacion/" + Localpoliza + "/" + Time;
            //string ruta = Server.MapPath("/Temporal/" +  Localpoliza + "/" + Time);
            try
            {

                //verificamos si llegaron los archivos o no 
                if (Request.Files.Count > 0)
                {

                    if (files.Count > 0)
                    {

                        // String para el directorio donde se carara el archivo temporal...
                        foreach (var item in onfile2)
                        {
                            listFilesToDelete += item.FileName + ",";

                            var NombreArchivo = Path.GetFileName(item.FileName);
                            string filename = "";
                            var DirDestino = new DirectoryInfo(ruta);
                            var Archivo = new FileInfo(Path.Combine(DirDestino.FullName, NombreArchivo.ToString()));


                            //int sizeKB = Convert.ToInt32(sizebyte) / 1024;
                            //string size = sizeKB.ToString();
                            // long filesize = new System.IO.FileInfo(NombreArchivo).Length;

                            // Verificamos si el directorio existe para grabar el archivo...
                            if (DirDestino.Exists == false)
                            {
                                DirDestino.Create();
                            }

                            filename = string.Concat(Archivo);
                            FileInfo nuevo = new FileInfo(filename);
                            item.SaveAs(nuevo.ToString());




                            ViewBag.mensaje = "Documento  cargado exitosamente...";
                        }


                        //Envio de los archivos e informacion al frontend_________//

                        //FileInfo fi = new FileInfo(Archivo.ToString());
                        //long size = fi.Length;
                        //int size2 = Convert.ToInt32(size);
                        //int filesize = size2 / 1024; //---------
                        //string extension = Archivo.Extension.ToString();



                        respuesta[0] = "1";
                        //respuesta[1] = Time;
                        //respuesta[2] = paliza;
                        //respuesta[3] = Path.GetFileName(onfile.FileName);
                        //respuesta[4] = filesize + " KB";
                        //respuesta[5] = extension;


                    }
                    else
                    {
                        respuesta[0] = "0";
                    }
                }
                else
                {
                    respuesta[0] = "?";
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                respuesta[0] = "error";
            }

            respuesta[1] = listFilesToDelete;
            return Json(respuesta);

        }
        [HttpPost]
        public JsonResult ConsultaPoliza(string Referencia)
        {
            string Time = DateTime.Now.ToString("dd-MM-yyyy");
            string rutaTemp = GetPathServer(Referencia);
            //     @"//172.16.32.35/Digitalizacion/"+ poliza;
            string ruta = Server.MapPath("/Temporal");
            string[] Data = new string[5];
            Data[0] = "1";

            try
            {

                if (rutaTemp != "")
                {

                    var didestination = new DirectoryInfo(rutaTemp);



                    if (didestination.Exists == true)
                    {
                        string[] subdirectoryEntries = Directory.GetFiles(rutaTemp, "*.*", SearchOption.AllDirectories);
                        foreach (string subdirectory in subdirectoryEntries)
                        {
                            FileInfo info = new FileInfo(subdirectory);
                            //var rutatempfinal = Path.Combine(ruta, info.Name);
                            //FileInfo filetemppath = new FileInfo(rutatempfinal);
                            //if (filetemppath.Exists == false)
                            //{
                            //    System.IO.File.Copy(info.FullName, Path.Combine(ruta, info.Name));
                            //    // Do something with the Folder or just add them to a list via nameoflist.add();


                            //}
                            Data[4] += info.FullName + "*" + info.Name + "|";
                            Data[4].TrimEnd();
                        }
                    }
                }


               // string BatchString = "DG|" + "Ref." + Referencia;
                //Data[1] = BatchString;

                SqlConnection con = referencia.roscon();
                string stringcomando = " Select Poliza, [Nombre CLiente], PersonaNumero, Aseguradora From DB_Smartsys3.dbo.Vw_ConsultaPoliza "
                                      + " Where Upper(Poliza) = '" + Referencia + "' Group By Poliza, [Nombre CLiente], PersonaNumero, Aseguradora";


                con.Open();
                SqlCommand commando = new SqlCommand(stringcomando, con);
                SqlDataReader leer = commando.ExecuteReader();
                if (leer.Read())
                {


                    //Data[0] = leer[0].ToString();
                    //Data[1] = leer[1].ToString(); 
                    Data[0] = leer[2].ToString();
                    Data[2] = leer[1].ToString();
                    Data[1] = "DG | " + "Po." + Referencia.ToUpper() + "_" + "Id." + Data[0];                     
                    Data[3] = leer[3].ToString();
                }
            }
            catch (Exception ex)
            {
                Data[0] = "0";
                Data[1] = "";
            }
            finally
            {
                
            }

            Localpoliza = Referencia;

            return Json(Data.ToArray());
        }
        //Busca todos los arvhivos en temporal____________________________________//
        [HttpPost]
        public JsonResult erasefile(string filename, string feccha, string polizza)
        {
            string response = "";


            string ruta = Server.MapPath("/App_Data/Temporal/RosTemp_Digitalizacion/" + feccha + "/" + polizza + "/" + filename);
            var directorio = new DirectoryInfo(ruta);
            try

SmartSys/Views/Digitalizacion/CreateForm.cshtml
@{
    ViewBag.Title = "CreateForm";
}

<script src="~/Scripts/DigitalizacionScripts/Validaciones.js">
</script>

<div class="form-group dynamic-element" style="display:none">
    <div class="row">
        <div class="col-md-2"></div>
       
        <!-- Replace these fields -->
        @*<div class="col-md-4">
            <input type="text" class="form-control" name="" id="label" placeholder="Nombre del Campo" />

        </div>
        <div class="col-md-3">
            <select id="tipo" name="rol[]" class="form-control">
                <option selected disabled>Tipo de Campo</option>
                <option>Texto</option>
                <option>Texto Grande</option>
                <option>Fecha</option>
                <option>Lista</option>

            </select>
        </div>*@
        <!-- End of fields-->
        @*<div class="col-md-1">
            <p class="delete">x</p>
        </div>*@
    </div>
</div>
<!-- END OF HIDDEN ELEMENT -->

<div class="form-container">
    <form class="form-horizontal" id="formPlantilla">
        <fieldset>
            <!-- Form Name -->
            <legend class="title">Creacion de Plantilla</legend>

            <div class="dynamic-stuff">
                <table id="tableplantilla">
                    <tr>
                        <td style="position: relative;left: 228px;">
                            <input type="text" class="form-control" name="" id="label" placeholder="Nombre del Campo" />
                        </td>
                        <td style="position: relative;left: 230px;">
                            <select id="tipo" name="rol[]" class="form-control">
                                <option selected disabled>Tipo de Campo</option>
                                <option>Texto</option>
                                <option>Texto Grande</option>
                                <option>Fecha</option>
                                <option>Lista</option>

                            </select>
                        </td>
                        <td style="position: relative;left: 233px;top: 5px;">
                            <p class="delete">x</p>
                        </td>
                    </tr>
                    
                </table>
            </div>
            &nbsp;


            <!-- Button -->
            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">
                        <p class="add-one">+ Añadir Control</p>
                    </div>
                    <div class="col-md-5"></div>
                    <div class="col-md-6">
                        <button id="botonContinuar" name="singlebutton" class="btn btn-primary">Guardar Plantilla</button>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>

<!-- Modal -->
<div class="modal fade" id="ModalNombrePlantilla" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" style="max-width: 60%; height: 34%;" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalScrollableTitle">Vista Completa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="" class="needs-validation" action="" novalidate method="post">
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <span for="" class="sizaspan col-sm-auto col-form-label text-black-100 rounded">Nombre de la Plantilla:</span>
                            <div class="col-sm-auto">
                                <input type="text" class="form-control" name="" id="nombrePlantilla" placeholder="" />
                            </div>
                        </div>
                        &nbsp;
                        <div class="col-mb-6">
                            <button type="submit" id="botonGuardarPlantilla" class="btn btn-success col-md-6" style="width: 226px;">Guardar Plantilla</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<style>
    .form-container {
        padding: 10px;
        padding-bottom: 25px;
        margin: 0 auto;
        width: 65%;
        border-radius: 20px;
        background-color: #ececec;
    }

    .add-one {
        color: green;
        text-align: center;
        font-weigth: bolder;
        cursor: pointer;
        margin-top: 10px;
    }

    .delete {
        color: white;
        background-color: rgb(231, 76, 60);
        text-align: center;
        margin-top: 6px;
        font-weight: 700;
        border-radius: 5px;
        min-width: 20px;
        cursor: pointer;
    }

    #singlebutton {
        width: 100%;
        margin-top: 20px;
    }

    .title {
        text-align: center;
        font-size: 40px;
        margin-bottom: 40px;
    }

    .dynamic-element {
        margin-bottom: 0px;
    }
</style>
@section Scripts{
    <script>
        $(document).ready(function () {

            //Clone the hidden element and shows it
            $('.add-one').click(function () {
                //$('.dynamic-element').first().clone().appendTo('.dynamic-stuff').show();
                let html = "";

                html += '<tr><td style="position: relative;left: 228px;"><input type="text" class="form-control" name="" id="label" placeholder="Nombre del Campo" /></td>';
                html += '<td style="position: relative;left: 230px;"><select id="tipo" name="rol[]" class="form-control"><option selected = "" disabled = "">Tipo de Campo</option><option>Texto</option><option>Texto Grande</option><option>Fecha</option><option>Lista</option></select ></td>';
                html += '<td style="position: relative;left: 233px;top: 5px;"><p class="delete" onclick="DeleteItemsTable(this)">x</p></td></tr>';
                $('.dynamic-element').show()
                $("#tableplantilla").append(html);
           
            });
        })
        $('#botonGuardarPlantilla').on('click', function (e) {
            e.preventDefault();
            savePlantilla();
            $('#ModalNombrePlantilla').modal('hide');
        });

        $('#botonContinuar').on('click', function (e) {
            e.preventDefault();
            $('#ModalNombrePlantilla').modal('show');
        });

        //Attach functionality to delete buttons
        function DeleteItemsTable(items) {
            var td = items.parentNode;
            var tr = td.parentNode; // the row to be removed
            tr.parentNode.removeChild(tr);
        }


    </script>
}

SmartSys/Views/Digitalizacion/IndexDig.cshtml
@{
    ViewBag.Title = "IndexDig";
}

<style>
        .container {
            max-width: 960px;
        }

        .navbar-survival101 {
            background-color: #2B6DAD;
        }
            /* .navbar-survival101 .navbar-brand {
      margin-right: 2.15rem;
      padding: 3px 0 0 0;
      line-height: 36px;
    } */

            .navbar-survival101 .navbar-brand img {
                vertical-align: baseline;
            }

        .navbar-expand-lg .navbar-nav .nav-link {
            color: #fff;
        }

        .search-box {
            position: relative;
            height: 34px;
        }

            .search-box input {
                border: 0;
                border-radius: 3px !important;
                padding-right: 28px;
                font-size: 15px;
            }

            .search-box .input-group-btn {
                position: absolute;
                right: 0;
                top: 0;
                z-index: 999;
            }

                .search-box .input-group-btn button {
                    background-color: transparent;
                    border: 0;
                    padding: 4px 8px;
                    color: rgba(0,0,0,.4);
                    font-size: 20px;
                }

                    .search-box .input-group-btn button:hover,
                    .search-box .input-group-btn button:active,
                    .search-box .input-group-btn button:focus {
                        color: rgba(0,0,0,.4);
                    }

        @@media (min-width: 992px) {
            .navbar-expand-lg .navbar-nav .nav-link {
                padding-right: .7rem;
                padding-left: .7rem;
            }

            .search-box {
                width: 300px !important;
            }
        }

        .caroulsel {
            width: 100%;
            overflow: hidden;
            padding: 5px 0 5px 5px;
        }

        .caroulsel-wrap {
            white-space: nowrap;
        }

            .caroulsel-wrap a {
                display: inline-block;
                width: 134px;
                height: 140px;
                margin-right: 20px;
            }
</style>

<div class="row justify-content-end">
    <a href="/Home/Index" class="btn btn-primary "><i class="fas fa-reply"></i> Volver</a>
</div>
    &nbsp;
<section class="caroulsel">
    <div class="caroulsel-wrap d-flex justify-content-center">
        <a href="/Digitalizacion/Scan" data-toggle='tooltip' data-placement='top' title='Registro De Expediente'><img class="img-fluid" src="~/Plantilla/dist/img/scan-.png" alt="Alternate Text" /></a>
        <a href="/Digitalizacion/Indexa" data-toggle='tooltip' data-placement='top' title='Indexar Documentos'><img class="img-fluid" src="~/Plantilla/dist/img/IndexIcon.png" alt="Alternate Text" /></a>
        <a href="/Digitalizacion/IndexConsulta" data-toggle='tooltip' data-placement='top' title='Consulta De Expedientes'> <img class="img-fluid" src="~/Plantilla/dist/img/IndexarIcon2.png" alt="Alternate Text" /></a>
        <a href="#" data-toggle='tooltip' data-placement='top' title='Creacion de Plantillas'><img class="img-fluid" src="~/Plantilla/dist/img/IconCreateForm.png" alt="Alternate Text" /></a>
    </div>

</section>

SmartSys/Views/Digitalizacion/Scan.cshtml
@{
    ViewBag.Title = "Scan";
}


<!-- Page Content -->
<!----libreria de script-->
<head>

    <script src="~/Scripts/DigitalizacionScripts/DigitalizacionJS.js">

    </script>

    <!--modal style-->
    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content/Box */
        .modal-content {
            background-color: #fefefe;
            margin: 15% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 80%; /* Could be more or less, depending on screen size */
        }

        /* The Close Button */
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

            .close:hover,
            .close:focus {
                color: black;
                text-decoration: none;
                cursor: pointer;
            }
    </style>

</head>

@*@using (Html.BeginForm("uploadfile", "Digitalizacion", FormMethod.Post,
                                   new { enctype = "multipart/form-data" }))
    {*@

<div class="justify-content-end">
    <a href="/Digitalizacion/IndexDig" class="btn btn-primary float-right"><i class="fas fa-reply"></i> Volver</a>

</div>
<div class="container-fluid  overflow-auto" runat="server">

    <div class="row">

        <div class="col-5">
            <form name="formulario" id="formulario" style="padding:50px;width: 85%;">


                <div class="form-group">
                    <label>Póliza:</label>
                    <input id="txtpoliza" type="text" class="form-control" placeholder="Digite Una Póliza" maxlength="30" required style="text-transform:uppercase"/>
                </div>
                <div class="form-group">
                    <label>Cliente:</label>
                    <input id="txtcliente" type="text" class="form-control" maxlength="30" disabled />
                </div>
                <div class="form-group">
                    <label>Batch:</label>
                    <input disabled id="txtBatch" type="text" class="form-control" />
                </div>
                @*<div class="form-group">
                        <table class="table-sm">
                            <tr>
                                <td>
                                    <i class="fa fa-compact-disc"></i>
                                    <input type="checkbox" id="Disco" />
                                    <label class="form-check-label">Guardar en disco</label>

                                    <i class="fas fa-server ml-2"></i>
                                    <input type="checkbox" id="Ordenador" />
                                    <label class="form-check-label">Guardar en db</label>
                                </td>

                            </tr>
                        </table>

                    </div>*@
                <div class="form-group">
                    <input type="file" name="file" id="file" class="privatefile" multiple />
                    <br />
                    <div class="list-group-item" id="file-list-display" style="
    height: 226px;
    overflow: scroll;
">

                    </div>
                </div>

                <div class="form-group">

                    <button id="btnConsultaExp" type="button" class="btn btn-success col-sm-5" style="margin-top:3em">Consultar Expedientes</button>
                    @*<button id="btnRegistrarArch" type="button" class="btn btn-success col-sm-5" style="margin-top:3em; margin-left:2em; height:62px">Registrar Archivos</button>*@
                    <button id="btnRegistrarExp" type="button" class="btn btn-success col-sm-5" style="margin-top:3em">Registrar Expediente</button>
                </div>
            </form>
        </div>
        <div class="col-6">
            <label style="margin-top:2em">Previsualización:</label>
            <div class="container-fluid">
                <div class="" style="margin-top:1em">
                    <iframe id="image" style="width:100%; height:36em">
                    </iframe>
                </div>
            </div>
        </div>

    </div>
    <div class="modal fade bd-example-modal-xl" id="myModal" tabindex="3100" style="z-index:3100" role="dialog" data-backdrop="false" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl" style="top: calc(25% - 300px);" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="">Detalle Expediente</h5>
                    <button type="button" class="close" id="closeConsulta" onclick="" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="row">
                    <div class="col-5">
                        <label style="margin-top:2em" for="Cliente">Lista de Documentos:</label>
                        <div class="list-group" id='file-list-displayScan' style="height: 23%;overflow:scroll">
                        </div>
                    </div>
                    <div class="col-6">
                        <label style="margin-top:2em">Previsualización:</label>
                        <div class="container-fluid">
                            <div class="" style="margin-top: 0em;width: 122%;height: 727px;">
                                <iframe id="imageConsultScan" src="" style="height: 73%;width: 98%;overflow:scroll;"></iframe>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>






@*<div id="myModal" class="modal">

    <div class="modal-content">
        <span class="close">&times;</span>
        <div class="container-fluid shadow overflow-auto">
            <div class="row">
                <div class="col-5">
                    <label style="margin-top:2em" for="Cliente">Lista de Documentos:</label>
                    <div class="list-group" id='file-list-displayScan' style="height: auto;overflow:scroll">
                    </div>
                </div>
                <div class="col-6">
                    <label style="margin-top:2em">Previsualizacion:</label>
                    <div class="container-fluid">
                        <div class="" style="margin-top: 0em;width: 122%;height: 727px;">
                            <iframe id="imageConsultScan" src="" style="height: 73%;width: 98%;overflow:scroll;"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>*@

<!-- The Modal para indexar un archivo-->
@*<div id="RegModal" class="modal">


        <div class="modal-content">
            <span id="close2" class="close">&times;</span>
            <div id="tabblabox">
                <table id="mytable2" class="table table-striped table-condensed">

                    <tr>
                        <th>
                            Poliza:
                        </th>
                        <th>
                            <input id="txtpoliza2" disabled />
                        </th>
                        <th>
                            Aseguradora:
                        </th>
                        <th>
                            <input id="txtaseguradora" style="width:80em" disabled />
                        </th>

                    </tr>

                    <tr>
                        <th>
                            Tilutar:
                        </th>
                        <th>
                            <input id="txtcliente2" style="width:80em" disabled>
                        </th>
                        <th>
                            Dependientes:
                        </th>
                        <th>
                            <input id="txtdependientes" />
                        </th>
                    </tr>

                    <tr>
                        <th>
                            Batch:
                        </th>
                        <th>
                            <input id="txtbatch2" disabled style="width:80em" />
                        </th>
                        <th>
                            Parentesco:
                        </th>
                        <th>
                            <input id="txtparentesco" />
                        </th>
                    </tr>

                    <tr>

                        <th>
                            Tipo Documento:
                        </th>
                        <th>
                            <select id="txttipodocumento">
                                <option id="0">Endoso</option>
                                <option id="1">Formulario afiliación</option>
                                <option id="2">Carné SM</option>
                                <option id="3">Carné FM</option>
                                <option id="4">Análisis renovación</option>
                                <option id="5">Reclamo</option>
                                <option id="6">Cheque</option>
                                <option id="7">Completivo reclamo</option>
                                <option id="8">Condiciones aceptación </option>
                                <option id="9">Contrato</option>
                                <option id="10">Formulario debida diligencia </option>
                                <option id="11">Cotización</option>
                                <option id="12">Minuta</option>
                            </select>
                        </th>
                        <th>
                            No.Reclamo:
                        </th>
                        <th>
                            <input id="txtnoreclamo" required />
                        </th>
                    </tr>
                </table>
            </div>
            <div class="form-group">
                <button id="btnconfirmaindexar" type="button" class="btn btn-success col-sm-5" style="margin-top:3em">Indexar</button>
            <button id="btnfilanizar" type="button" class="btn btn-success col-sm-5" style="margin-top:3em">Finalizar</button>

            </div>
        </div>

    </div>*@




@*}*@

@section Scripts{
<script type="text/javascript">
        $(document).ready(function () {
            $('#myModal').on('hidden.bs.modal', function (e) {
                $("#file-list-displayScan a").removeClass("active")
                $("#imageConsultScan").attr("src", "")
                $("#myModal").modal("hide")
            })
        });
    </script>
}

SmartSys/Views/Digitalizacion/indexardocumentos.cshtml
@{
    ViewBag.Title = "indexardocumentos";
}

<h2>indexardocumentos</h2>